# Generated by Django 4.2.5 on 2023-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_de_interesse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_interesse',
            name='caminho_imagem',
            field=models.ImageField(upload_to='ponto_de_interesse/'),
        ),
    ]
