# Generated by Django 4.2.5 on 2023-09-26 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponto_de_interesse', '0002_alter_ponto_interesse_caminho_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('ponto_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponto_de_interesse.ponto_interesse')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
